# Generated by Django 3.2 on 2021-05-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210505_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
    ]
