# Generated by Django 3.2 on 2021-05-07 22:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_link_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
