# Generated by Django 3.2 on 2021-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_link_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='email_user',
            field=models.CharField(default='user', max_length=250),
        ),
    ]
